// --- Fallback Polls (for API failures) ---
const FALLBACK_POLLS = [
    { type: 'trivia', question: "What is the term for a neural network that processes data in sequences, such as text or time series?", options: ["Convolutional Neural Network", "Recurrent Neural Network", "Transformer", "Autoencoder"], correctAnswerIndex: 1, explanation: "Recurrent Neural Networks (RNNs) process data in sequences by maintaining hidden states that capture information from previous steps, making them ideal for sequential data like text or time series." },
    { type: 'trivia', question: "Which technique prevents overfitting by randomly dropping neurons during training?", options: ["Batch Normalization", "Dropout", "Data Augmentation", "Early Stopping"], correctAnswerIndex: 1, explanation: "Dropout randomly deactivates neurons during training to prevent the network from becoming too dependent on specific neurons, improving generalization." },
    { type: 'trivia', question: "What type of learning uses labeled data to train a model?", options: ["Unsupervised Learning", "Reinforcement Learning", "Supervised Learning", "Self-Supervised Learning"], correctAnswerIndex: 2, explanation: "Supervised Learning uses labeled datasets with input-output pairs to train models to predict outputs from new inputs." },
    { type: 'trivia', question: "What is the name of the attention mechanism introduced in the 'Attention Is All You Need' paper?", options: ["Self-Attention", "Multi-Head Attention", "Cross-Attention", "Scaled Dot-Product Attention"], correctAnswerIndex: 1, explanation: "The Transformer architecture uses Multi-Head Attention, which allows the model to focus on different parts of the input simultaneously." },
    { type: 'trivia', question: "Which metric measures the proportion of true positives among all predicted positives?", options: ["Recall", "Precision", "F1 Score", "Accuracy"], correctAnswerIndex: 1, explanation: "Precision measures how many of the positive predictions are actually correct, calculated as TP/(TP+FP)." },
    { type: 'trivia', question: "What is the main purpose of the embedding layer in NLP models?", options: ["Reduce dimensionality", "Convert words to numerical vectors", "Apply activation functions", "Normalize inputs"], correctAnswerIndex: 1, explanation: "Embedding layers convert categorical text data into dense numerical vectors that capture semantic meaning." },
    { type: 'trivia', question: "Which algorithm is commonly used for clustering in unsupervised learning?", options: ["Linear Regression", "K-Means", "Decision Tree", "Naive Bayes"], correctAnswerIndex: 1, explanation: "K-Means is a popular clustering algorithm that partitions data into K clusters based on distance to centroids." },
    { type: 'trivia', question: "What does the term 'epoch' refer to in neural network training?", options: ["One forward pass", "One complete pass through the dataset", "One gradient update", "One batch processing"], correctAnswerIndex: 1, explanation: "An epoch is one complete iteration through the entire training dataset during model training." },
    { type: 'trivia', question: "Which activation function outputs values between 0 and 1, commonly used in output layers for probabilities?", options: ["ReLU", "Sigmoid", "Tanh", "Softmax"], correctAnswerIndex: 1, explanation: "The Sigmoid function squashes values to the (0,1) range, useful for binary classification output layers." },
    { type: 'trivia', question: "What is the purpose of a loss function in machine learning?", options: ["Increase model complexity", "Measure prediction error", "Normalize data", "Select features"], correctAnswerIndex: 1, explanation: "Loss functions quantify the difference between predicted and actual values, guiding the optimization process." },
    { type: 'trivia', question: "Which technique adjusts model weights based on the gradient of the loss function?", options: ["Forward Propagation", "Backpropagation", "Regularization", "Cross-Validation"], correctAnswerIndex: 1, explanation: "Backpropagation computes gradients of the loss with respect to weights, enabling gradient descent optimization." },
    { type: 'trivia', question: "What is transfer learning in deep learning?", options: ["Training from scratch", "Using pre-trained models for new tasks", "Distributing training across devices", "Parallel model training"], correctAnswerIndex: 1, explanation: "Transfer learning leverages knowledge from pre-trained models on large datasets to improve performance on related tasks." },
    { type: 'trivia', question: "Which layer type is specifically designed to extract features from images?", options: ["Dense Layer", "Dropout Layer", "Convolutional Layer", "Recurrent Layer"], correctAnswerIndex: 2, explanation: "Convolutional layers use filters to detect spatial patterns like edges, textures, and shapes in images." },
    { type: 'trivia', question: "What is the vanishing gradient problem?", options: ["Gradients become too large", "Gradients become negligible during backpropagation", "Model converges too slowly", "Training data is lost"], correctAnswerIndex: 1, explanation: "In deep networks, gradients can become extremely small, preventing effective weight updates in early layers." },
    { type: 'trivia', question: "What does GPT stand for?", options: ["General Pre-trained Transformer", "Gaussian Probabilistic Transform", "Global Processing Technology", "Graphical Prediction Tool"], correctAnswerIndex: 0, explanation: "GPT stands for Generative Pre-trained Transformer, a language model architecture using transformer decoders." },
    { type: 'trivia', question: "Which metric is best for imbalanced classification datasets?", options: ["Accuracy", "Precision", "F1 Score", "Mean Squared Error"], correctAnswerIndex: 2, explanation: "F1 Score balances precision and recall, making it suitable for imbalanced datasets where accuracy can be misleading." },
    { type: 'trivia', question: "What is the purpose of a validation set in machine learning?", options: ["Final testing", "Hyperparameter tuning", "Training the model", "Data preprocessing"], correctAnswerIndex: 1, explanation: "Validation sets help tune hyperparameters and evaluate model performance without touching test data." },
    { type: 'trivia', question: "Which optimization algorithm uses momentum to accelerate convergence?", options: ["SGD", "Adam", "Batch Gradient Descent", "Mini-Batch GD"], correctAnswerIndex: 1, explanation: "Adam combines momentum with adaptive learning rates, making it effective for many deep learning applications." },
    { type: 'trivia', question: "What is few-shot learning?", options: ["Learning from many examples", "Learning from a few examples", "Learning without examples", "Learning with no data"], correctAnswerIndex: 1, explanation: "Few-shot learning enables models to learn new tasks from only a small number of examples." },
    { type: 'trivia', question: "What is the role of the tokenizer in NLP models?", options: ["Train the model", "Split text into tokens", "Evaluate performance", "Store embeddings"], correctAnswerIndex: 1, explanation: "Tokenizers convert raw text into tokens (words, subwords, or characters) that models can process." }
];

module.exports = { FALLBACK_POLLS };
